name: Build libxml2

on:
  workflow_dispatch:
    inputs:
      libxml2_version:
        description: 'libxml2 version'
        required: true
        default: '2.12.3'

jobs:

  build-android-libxml2:

    runs-on: ubuntu-latest
    env:
      LIBXML2_VERSION: ${{ github.event.inputs.libxml2_version || '2.12.3'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout libxml2 source code
        uses: actions/checkout@v4
        with: 
          repository: GNOME/libxml2
          ref: refs/tags/v${{ env.LIBXML2_VERSION }}
          path: build/android/libxml2/build/libxml2-${{ env.LIBXML2_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c
          local-cache: true
          
      - name: Build from source
        run: |
          chmod +x scripts/android/libxml2/build.sh
          ./scripts/android/libxml2/build.sh ${{ steps.setup-ndk.outputs.ndk-path }} build/android/libxml2 ${{ env.LIBXML2_VERSION }} --skip-prepare
        env:
          NDK_DIR: ${{ steps.setup-ndk.outputs.ndk-path }}
          LIBXML2_VERSION: ${{ env.LIBXML2_VERSION }}
        
      - name: Upload libxml2 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deps-android-libxml2
          path: build/android/libxml2/install
          overwrite: true
